ci:
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        args: [--cache-location=.prettier_cache/cache]
        exclude_types: ["json", "markdown"]
  - repo: local
    hooks:
      - id: remark
        name: remark
        language: node
        entry: remark
        types_or: [markdown, json]
        args: ["--frail", "--quiet"]
        additional_dependencies:
          - remark
          - remark-lint
          - remark-lint-no-html
          - remark-cli
          - remark-preset-lint-consistent
          - remark-preset-lint-markdown-style-guide
          - remark-preset-lint-recommended
          - remark-validate-links
          - remark-gfm
