name: Check Markdown and Examples
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.owner == "stac-extensions"
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm test
